spring:
  application:
    # 对应config server所获取的配置文件的 {application}
    name: application
  cloud:
    config:
      # 指 config server 地址
      uri: http://localhost:8080/
      # 指定 config server 里的 {profile}
      profile: dev
      # 指定Git仓库分支，对应config server的{label}
      label: master
  rabbitmq:
    host: 49.234.118.253
    username: admin
    password: wadzxqes7
  datasource:
      url: jdbc:mysql://47.94.104.85:3306/yr_account?charaterEncoding=utf8&useSSL=false
      username: root
server:
  port: 9003